// SPDX-License-Identifier: AGPL-3.0-or-later

/**
 * Domain used for synthetic placeholder emails assigned to phone-only users.
 * Better Auth requires a non-null email on every user record, so phone-only
 * sign-ups receive a deterministic placeholder derived from their phone number.
 */
export const PLACEHOLDER_DOMAIN = 'phone.placeholder';

/**
 * Returns true if the given email is a synthetic placeholder — i.e. it was
 * generated by `makePlaceholderEmail` and does not represent a real address.
 */
export function isPlaceholderEmail(email: string | null | undefined): boolean {
	if (!email) return false;
	return email.endsWith(`@${PLACEHOLDER_DOMAIN}`);
}

/**
 * Generates a deterministic placeholder email for a phone number.
 * Strips all non-digit characters so the same number always produces the
 * same placeholder regardless of formatting.
 */
export function makePlaceholderEmail(phoneNumber: string): string {
	const digits = phoneNumber.replace(/[^0-9]/g, '');
	return `${digits}@${PLACEHOLDER_DOMAIN}`;
}
